name: publish
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Publish to lists.sh
        uses: neurosnap/lists-publish-action@v1.0.0
        with:
          user: erock
          key: ${{ secrets.PRIVATE_KEY }}
