name: publish
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Publish to lists.sh
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /
          remote: /
          host: lists.sh
          username: erock
          privateKey: ${{ secrets.PRIVATE_KEY }}
